apiVersion: v1
kind: Secret
metadata:
  name: board-db-secret
  namespace: board-service
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mydb:3306/board"
  SPRING_DATASOURCE_USERNAME: "board_user"
  SPRING_DATASOURCE_PASSWORD: "board_pass"
