apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-db
  namespace: board-service
  labels:
    app: board-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board-db
  template:
    metadata:
      labels:
        app: board-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpass
            - name: MYSQL_DATABASE
              value: userdb
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: "1234"
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: board-db
  namespace: board-service
spec:
  selector:
    app: board-db
  ports:
    - port: 3306
      targetPort: 3306