namespace: board-service
replicaCount: 2

image:
  repository: gyurihwang/contest-18-image-board
  tag: "{BUILD_DATE_TIME}"
  pullPolicy: Always


service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod

envFrom:
  - secretRef:
      name: boardr-service-secret
  - secretRef:
      name: board-db-secret
