name: Release Helm Chart

on:
  push:
    paths:
      - "helm/**"   # helm/ 폴더 안 변경 있을 때만
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Package Helm Chart
        run: |
          cd helm
          helm package .
          helm repo index . --url https://paassible.github.io/BE1/

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./helm
          publish_branch: gh-pages
